package com.example.grocerywise.models

data class GroceryItem(
    val uid: String = "",
    val name: String = "",
    val quantity: Int = 1,
    val estimatedPrice: Double = 0.0,
    val upc: String = "",
    val isChecked: Boolean = false,
    val imageUrl: String? = null,
)

data class InventoryItem(
    var id: String? = null, // Used to store the key generated by the database
    val name: String = "",
    val quantity: Int = 0,
    val upc: String? = null,
    val expirationDate: String? = null,
    val imageUrl: String? = null,
)

data class GroceryListItem(
    var id: String? = null, // Used to store the key generated by the database
    val name: String = "",
    val quantity: Int = 0,
    val estimatedPrice: Double? = null,
    val upc: String? = null,
    val isChecked: Boolean = false,
    val imageUrl: String? = null,
)
