package com.example.grocerywise.models

data class GroceryItem(
    var id: String? = null, // Used to store the key generated by the database
    val name: String = "",
    val quantity: Int = 0,
    var estimatedPrice: Double = 0.0,
    val upc: String? = null,
    var isChecked: Boolean = false,
    val imageUrl: String? = null,
)
