package com.example.grocerywise.models

data class InventoryItem(
    var id: String? = null, // Used to store the key generated by the database
    val name: String = "",
    val quantity: Int = 0,
    val upc: String? = null,
    val expirationDate: String? = null,
    val imageUrl: String? = null,
)

